config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_vimrc:
    dst: ~/.vimrc
    src: .vimrc
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: .tmux.conf 
  f_zshrc:
    dst: ~/.zshrc
    src: .zshrc 
profiles:
  home:
    dotfiles:
    - f_vimrc
    - f_tmux.conf
    - f_zshrc
